#NOCHECK
# -*- coding: utf-8 -*-
from .calendar.blockinghistory import BlockingHistory
from .calendar.hebergementblockinghistory import HebergementBlockingHistory
from .calendar.reservationproprio import ReservationProprio
from .hebergement.hebergement import Hebergement
from .hebergement.hebergementmaj import HebergementMaj
from .hebergement.linkhebergementepis import LinkHebergementEpis
from .hebergement.linkhebergementmetadata import LinkHebergementMetadata
from .hebergement.linkhebergementmetadataupdate import LinkHebergementMetadataUpdate
from .hebergement.metadata import Metadata
from .hebergement.metadatatype import MetadataType
from .hebergement.typehebergement import TypeHebergement
from .hebergement.typetablehoteofhebergementmaj import TypeTableHoteOfHebergementMaj
from .info.infotouristique import InfoTouristique
from .info.typeinfotouristique import TypeInfoTouristique
from .info.infopratique import InfoPratique
from .info.typeinfopratique import TypeInfoPratique
from .map.mapblacklist import MapBlacklist
from .map.mapprovider import MapProvider
from .proprio.civilite import Civilite
from .proprio.proprio import Proprio
from .proprio.propriomaj import ProprioMaj
from .tablehote import TableHote
from charge import Charge
from commune import Commune
from logitem import LogItem
from maisontourisme import MaisonTourisme
from province import Province
